### ISSUE TITLE
Create and implement appt.controllers.ts

### ISSUE THREAD

**Issue by kishanpatel97** [kishanpatel97/APPT#9]
Define CRUD and async operations for the API in controller file

**Comment by b-chang** [comment]
We should discuss on what basic operations are necessary before even starting the controllers or the routes
A basic data model should be built to construct what types of routes we need and what needs to be returned from the controllers

**Comment by b-chang** [comment]
I bundled in some changes that modernized import and exports from ES5 to ES6 syntax as well
